version: '2'
services:
    consul:
        image: "opt/consul"
        networks:
            - opt
    gate-go:
        image: "opt/gate-go"
        #ports:
        #    - "80:80"
        networks:
            - opt
    nginx:
        image: "opt/nginx"
        ports:
            - "80:80"
        networks:
            - opt
        depends_on:
            - gate-go
networks:
    opt:
